### PR TITLE
Improved demo support in the Makefile

### PR DESCRIPTION
**Pull request by neuromancer**
This PR allows users to quickly test Carnage3D executing:

```
$ make
$ make demo
$ make run
``` 

The demo will be download from the official Rockstar website, extracted and configured to run.

### CODE REVIEW

**Comment by codenamecpp** [comment]
I think it is actually a good idea.

But I have few complaints:
1) Script will overwrite user's settings file and and he won’t be happy :(
I think that new command line param must be added to specify gta1 data location and it will take precedence over the one that comes from config file.
2) The first thing I think about when see the word 'demo' is game demonstration record. I thing it will be better rename to 'demoversion'
So, instead of 'demo' command I would like to see 'get_demoversion'.
'run' should be left as it was and add new command 'run_demoversion'.

I will put gamedata/demoversions directory to git ignore. All demos can be put there.

**Comment by codenamecpp** [comment]
- Added command line param "-gtadata".
- Added gamedata/demoversions to .gitignore

**Comment by neuromancer** [comment]
I agree with your remarks. Feel free to edit this PR!

**Comment by neuromancer** [comment]
It is also useful to reorganize a little the README to put this information somewhere, probably in a `Getting started` section or something like that.

**Review by codenamecpp — CHANGES_REQUESTED** [review]
Please test

**Comment by neuromancer** [comment]
Looks good to me!

**Review by codenamecpp — APPROVED** [review]

**Comment by codenamecpp** [comment]
OK, done. Thanks.

**Pull request merged**
